import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, ClerkLoading, ClerkLoaded } from "@clerk/nextjs";
import Headre from "@/components/Headre";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
      <ClerkLoading>
      <p className="text-center ">Loading...</p>
      </ClerkLoading>
      <ClerkLoaded>
      <Headre/>
      {children}
      </ClerkLoaded>
      </body>
    </html>
    </ClerkProvider>
  );
}
